### PR TITLE
Style HoneyDo Navbar component

### LINKED ISSUE #37: 20. Styling- Navbar
### **Summary**
Add styling to the Navbar component. 

### **Acceptance criteria**
- [ ]  Style component to match wireframe at: https://www.figma.com/file/N8D1ermyhj04g2X9WAxhjc/TCL-47-Honeydew?node-id=0%3A1

### **Notes**

If you have any questions, don't hesitate to message the team in Slack.

### PR DESCRIPTION
**Pull request by wheninseattle**
Co-authored-by: acole <a-cole55@users.noreply.github.com>

## Description

This feature branch styles the 'Navbar' for the application. Navbar is in quotes, because this bar isn't actually being utilized for navigation. 

## Related Issue

close #37 

## Acceptance Criteria

- [ ]  Style component to match wireframe at: https://www.figma.com/file/N8D1ermyhj04g2X9WAxhjc/TCL-47-Honeydew?node-id=0%3A1

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

HoneyDon't

HoneyDont-Navbar

### After

HoneyDo

HoneyDo-Navbar

## Testing Steps / QA Criteria

1. `git pull AC-WN-Navbar`
2. `npm start`
3. Check out the new navbar!

### CODE REVIEW

**Review by tmflower — APPROVED** [review]
Non-navigating "navbar" looks great! I like the incorporation of the fruit for the letter o and of course the little bee! Maybe we should be calling this a banner or something, instead of navbar.

**Review by YolandaHaynes — APPROVED** [review]
Really love the new 'navbar'! I really love how you incorporated the honeydew's pic and tied it with the word and also the cute little flying bee 🥰 .  Loving seeing the play on words. 
Similar to what @tmflower mentioned. My mind went with 'banner' or 'header' however this is your app. So as a team, if you all want to keep it 'navbar', there's nothing wrong with keeping it!
TIL (Today I learned) about ```env()``` ! This was my first time seeing this. Since this is new to me, is there a reason why you went with ```env()``` function instead of Material UI's media query? 
Other than that.......Fantastic job making such a cute 'navbar'!!!! ❤️

**Comment by wheninseattle** [comment]
@YolandaHaynes today _I_ learned about`env()`! I believe that was part of the initial code. Thanks for reviewing this! Great point about 'banner'; I'll make that change!

**Review by veeteeran — APPROVED** [review]
@wheninseattle Looks like you have a minor conflict to resolve but I'll approve so you can try to merge this before the sync. I too love the banner and the subtle 'ne' the bee spells out!

**Review by mariahschock — APPROVED** [review]

**Review by a-cole55 — APPROVED** [review]
Looks fabulous!

**Pull request merged**
