### PR TITLE
rendering list items

### LINKED ISSUE #1: 1. As a user, I want to read the names of all of the items in my shopping list
## Summary

The most important feature of our app is the ability to look at what's on the list, so the user knows what they need to buy. The `List` component is the best place in our code to do that. In fact, this feature is already partially implemented. Refer to the acceptance criteria in this issue, and the existing code, to understand the work that remains.

The `List` component is rendered on the `/list` page. Because the navigation links are currently broken, you'll have to type that path into your browser's address bar.

## Acceptance criteria
- [ ] The `streamListItems` function is used in `App.jsx` to get the items in the current list from the Firestore database
- [ ] The list is passed into the `List` component as a prop named `data`
- [ ] In `List.jsx`, the `ListItem` component is used to render the name of each item

## Notes
- ⚠️ Your **only goal** is to make sure that the names of the items render as expected. You might be tempted to modify `ListItem.jsx` to show more information – you will do that **later**. If you want a peek at the future, [this wireframe](https://github.com/the-collab-lab/smart-shopping-list/blob/main/_resources/wireframes/list-populated.png) is what your list could look like closer to the end of the project.
- The data you need is already being passed into the `List` component. What steps do you need to take in order to render it?

### PR DESCRIPTION
**Pull request by mariahschock**
## Description

This PR updates the List component so that for each item in the current list in the database, it renders a ListItem component and displays the name of the item when the user is at the /list route.

## Related Issue

closes #1

## Acceptance Criteria

- [✓ ] The streamListItems function is used in App.jsx to get the items in the current list from the Firestore database
- [✓ ] The list is passed into the List component as a prop named data
- [✓ ]  In List.jsx, the ListItem component is used to render the name of each item

## Type of Changes

Put an `✓` for the applicable box:

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓ | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before
before

### After
after

## Testing Steps / QA Criteria

- Navigate to branch TF-MS-list-feature
- Run npm start
- Manually type the route /list to navigate to the list view and the items should be visible.

### CODE REVIEW

**Review by wheninseattle — CHANGES_REQUESTED** [review]
Great job getting the data to map to an instance of the ListItem component for each item!
I ran the code and got two errors in the console:

- Error 1:  'Each child in a list should have a unique "key" prop.'
- The key may need to go in the html list item tag itself.
- Error 2: 'validateDOMNesting(...): html list item tag cannot appear as a descendant of html list item tag'
- It looks like the DOM is grumpy that a html list item tagis being returned within another html list item tag. Perhaps use the tag either in the List component or in the ListItem component, but not both.

Other than that, it looks great, @mariahschock & @tmflower!

**Comment by tmflower** [comment]
Thanks, @Weston. I think if we modify the way the map method is written slightly, it will solve both problems. So the only thing inside the <ul> tags would be: 

`{data.map(item => <ListItem name={item.name} key={item.id}/>)}`

What do you think, @Mariah?

**Comment by a-cole55** [comment]
I was coming to make the same suggestions as @wheninseattle. 
@tmflower with your proposed changes, I think everything looks good. Great job.

I did have a question... with your initial code, you all used the spread syntax to render each item name into the List Item component (ex. <ListItem key={item.name + i} {...item} />. I have never seen that done before which is cool and seems like a simpler way to do name = {item.name}. 
Why did you decide to change it?

**Review by a-cole55 — DISMISSED** [review]
I was coming to make the same suggestions as @wheninseattle.
@tmflower with your proposed changes, I think everything looks good. Great job.

I did have a question... with your initial code, you all used the spread syntax to render each item name into the List Item component (ex. <ListItem key={item.name + i} {...item} />. I have never seen that done before which is cool and seems like a simpler way to do name = {item.name}.
Why did you decide to change it?

**Comment by tmflower** [comment]
> I was coming to make the same suggestions as @wheninseattle. @tmflower with your proposed changes, I think everything looks good. Great job.
> 
> I did have a question... with your initial code, you all used the spread syntax to render each item name into the List Item component (ex. <ListItem key={item.name + i} {...item} />. I have never seen that done before which is cool and seems like a simpler way to do name = {item.name}. Why did you decide to change it?

Great question! I just defaulted to writing the code the way I normally would, since using spread in that way was new to me as well (introduced by Mariah). So it could stay in there; no changes have been made in the file yet.

**Comment by mariahschock** [comment]
Hey everyoneI I'd be happy to just remove the <li> tag. No errors pop up without it, we just lose our bullet points. 
{data.map((item, i) => <ListItem key={item.name + i} {...item} />)}

**Review by wheninseattle — DISMISSED** [review]

**Comment by wheninseattle** [comment]
Sounds like a great solution @mariahschock and @tmflower! I tried dropping the list tag from the List component and keeping it in the ListItem component and visa versa. I don't know which is the 'right way', but one of them left the bullet formatting intact. I approved the changes (still not sure if I'm doing this right!), so I think you just need to push your new code and get it reviewed by our mentors.

**Comment by YolandaHaynes** [comment]
Love seeing these conversations! This is great everyone. Just a rule of thumb, approve changes mean that the current code is good and ready to go. Currently, the changes still need to be made. So typically once the changes are made, the reviewers need to re-review it again to make sure the updated code is functional and working.
When you get the chance, @mariahschock and @tmflower please update the new changes and resubmit the new code to get it re-reviewed. 
This is great! You all rock!

**Comment by tmflower** [comment]
My apologies for the delays and hiccups with this! Hopefully I'll get faster and more comfortable with more practice.
Thank you for clarifying, @YolandaHaynes! And also for being so positive and encouraging about this whole process.   
I think it is now ready for re-review when you are able to get to it, @wheninseattle and @a-cole55 
Thanks for your patience!

**Review by a-cole55 — APPROVED** [review]
It looks great.

**Review by wheninseattle — APPROVED** [review]
Thanks for picking up those changes! Sorry for the delay; I've been trying to soak up the rest of vacation!

**Comment by tmflower** [comment]
Thank you, @a-cole55 and @wheninseattle !
This issue is ready for mentor review, @YolandaHaynes

**Comment by YolandaHaynes** [comment]
@tmflower no need to apologize! Also, thanks for tagging me again as a reminder. Really appreciate it!

**Review by YolandaHaynes — APPROVED** [review]
Good job fixing up the changes and deleting the comments. 
Woohoo! Awesome job working together @tmflower and @mariahschock you both rock!

**Pull request merged**
